name: Run Linter

on:
  push:
    branches:
      - HW6-testing
  pull_request:
    branches:
      - HW6-testing

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '27'
          distribution: 'oracle'

      - name: Download Checkstyle
        run: |
          curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-14.3.0/checkstyle-14.3.0-all.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c checkstyle.xml test/Usertest.java